const appHelper = require('../app');
const fs = require("fs");

test('it should', () => {
    const content = fs.readFileSync("../json/S01200HQT173.jpg.json");
    const textJson = JSON.parse(content);
    const mergedArray = appHelper.initLineSegmentation(textJson[0]['responses'][0]);
    expect(mergedArray).toEqual([ 'TESCO',
    'eactra',
    'CUMBERNAULD 0345 6779808',
    'KITTEN FOOD £3.50',
    'DIPPERS £2.50',
    'CKN DIPPERS £1.50',
    'CRISPS £1.24',
    'MINI CHEDDAR £1.00',
    'CRISPS £1.24',
    'MINI CHEDDAR £1.00',
    'T POTATO CAKES eU',
    '£0.50 £1.00',
    'CKN/MUSH SLICE £1.50',
    'CKN FINGERS £2.00',
    'TARTS £1.00',
    'CKN FINGERS £2.00',
    'TARTS £1.00',
    'SCONES £1.20',
    'BS 4 BURG BUNS 0.70',
    '£0.80',
    'BIN LINERS x £1.00',
    'KM SOFT THICK',
    'SWEETS',
    '£0.40 0.80',
    'GOV BAG CHARGE+x £0.05',
    'BISCUITS £1.00',
    '£1.29',
    'TIMEOUT',
    'TOTAL £27.32',
    'CASH',
    'CHANGE DUE £2.68',
    '830.00',
    'CLUBCARD STATEMENT',
    'CLUBCARD NUMBER xxxxxxxxxxxxxx0582',
    'QUALIFVING SPEND £27.27',
    'POINTS THIS VISIT 27',
    'TOTAL UP TO 07/11/16',
    'TESCO',
    'Bran',
    'Guarantee',
    'Today we were',
    'E O.35',
    'cheaper',
    'on your branded basket compared to',
    'Asda, Morrisons and Sainsbury\'s',
    'Our Brand Guarantee instantly matches',
    'your branded basket so you can always',
    'checkout with confi dence',
    'Branded grocery basket matched. For full',
    'terms visit tesco.com/brandguar antee',
    'by telling us about your trip',
    'at www.tescoviews.com',
    'and collect 25 Clubcard points.',
    'Terms and conditions apply' ]);
});
